<%
default_options = [
  '--publish-quiet',
  '--format pretty',
  '--format rerun --out tmp/rerun.txt',
  '--tags "not @wip"',
  '--tags "not @skip"',
  '--require features/support',
  '--require features/step_definitions'
].join(' ')
%>

default: <%= default_options %>

rerun: <%= default_options %> --strict @tmp/rerun.txt

wip: <%= default_options.gsub('--tags "not @wip"', '--tags @wip') %> --wip features

rack_test: <%= default_options %> --tags "not @javascript and not @skip and not @wip"

javascript: <%= default_options %> --tags "@javascript and not @skip and not @wip" --retry 2

a11y: <%= default_options %> --tags "@a11y and not @skip and not @wip" --retry 2
