# .github/workflows/a11y.yml
name: Accessibility Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  a11y_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
        ports:
         - 5432:5432
    env:
      DB_USER: postgres
      DB_PASSWORD: password
      RAILS_ENV: test
      RUBY_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      CANVAS_URL: http://bcourses.test.instructure.com
      CANVAS_TEST_USERNAME: ${{ secrets.CANVAS_TEST_USERNAME }}
      CANVAS_TEST_PASSWORD: ${{ secrets.CANVAS_TEST_PASSWORD }}
      CANVAS_TEST_NAME: ${{ secrets.CANVAS_TEST_NAME }}
    steps:
     - uses: actions/checkout@v3
     - name: Set up Ruby
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: 3.3.0
         bundler-cache: true
     - name: Install Dependencies
       run: |
         gem install bundler
         bundle install --jobs 4 --retry 3
     - name: Set up Database
       run: |
         bundle exec rails db:create
         bundle exec rails db:migrate
     - name: Create separate Chrome data directories
       run: |
         mkdir -p /tmp/chrome-data-cucumber
         mkdir -p /tmp/chrome-data-rspec
     - name: Run Cucumber Accessibility Tests
       run: bundle exec cucumber features/ --tag @a11y
       env:
         CHROME_DATA_DIR: /tmp/chrome-data-cucumber
     - name: Run RSpec Accessibility Tests
       run: bundle exec rspec spec/ --tag a11y
       env:
         CHROME_DATA_DIR: /tmp/chrome-data-rspec