name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    env:
      DB_USER: postgres
      DB_PASSWORD: password
      RAILS_ENV: production
      RUBY_ENV: production
      CANVAS_URL= https://ucberkeleysandbox.instructure.com
      CANVAS_CLIENT_ID = 265300000000000004
      CANVAS_APP_KEY = "LYk6KwLDAy2NkP6MaL7PfDDKC3xTPy6ukmDcWxNAryv328CrNGAttVuZh9xRyyNh"
      CANVAS_REDIRECT_URI = "http://localhost:3000"
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      CANVAS_URL: http://bcourses.test.instructure.com/

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Setup Database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate 