name: Cucumber Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cucumber:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    env:
      DB_USER: postgres
      DB_PASSWORD: password
      RAILS_ENV: test
      RUBY_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      CANVAS_URL: http://bcourses.test.instructure.com/
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true
    
    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        chrome-version: stable
    
    - name: Install Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV
        echo "Found Chromedriver at: $(which chromedriver)"
    
    - name: Verify Chrome and Chromedriver
      run: |
        google-chrome --version
        chromedriver --version
        echo "Chrome path: $(which google-chrome)"
        echo "Chromedriver path: $(which chromedriver)"
    
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    
    - name: Setup Database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
    
    - name: Create Chrome data directory
      run: mkdir -p /tmp/chrome-data-cucumber
    
    - name: Run Non-JavaScript Cucumber Tests
      run: |
        bundle exec cucumber features/ --tags 'not @skip and not @wip and not @javascript and not @a11y' --profile rack_test
      env:
        COVERAGE: "true"
        CI: "true"
    
    - name: Run JavaScript and A11y Cucumber Tests
      run: |
        DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        bundle exec cucumber features/ --tags '@javascript or @a11y' --profile selenium_chrome_headless
      env:
        CHROME_DATA_DIR: /tmp/chrome-data-cucumber
        COVERAGE: "true"
        CI: "true"
        SELENIUM_HEADLESS: "true"
        CHROMEDRIVER_PATH: $(which chromedriver)
        CHROME_FOR_TESTING_PATH: $(which google-chrome) 