name: Cucumber Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cucumber:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    env:
      # Do not install production/staging-only gems in test environment
      BUNDLE_WITHOUT: "production staging"
      DB_USER: postgres
      DB_PASSWORD: password
      RAILS_ENV: test
      RUBY_ENV: test
      CANVAS_URL: http://bcourses.test.instructure.com/
      CHROME_DATA_DIR: /tmp/chrome-data-cucumber
      COVERAGE: "true"
      SELENIUM_HEADLESS: "true"
      SELENIUM_DRIVER_VERSION: stable
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    # TODO: THis should work correctly using db:prepared but cuke/a11y tests fail
    #
    - name: Setup Database
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
    - name: Create Chrome data directory
      run: mkdir -p /tmp/chrome-data-cucumber
    - name: Run Non-JavaScript Cucumber Tests
      run: |
        bundle exec cucumber features/ --tags 'not @skip and not @wip and not @javascript and not @a11y' --profile rack_test
    - name: Run JavaScript Cucumber Tests
      run: |
        DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        bundle exec cucumber features/ --tags '@javascript and not @skip and not @wip and not @a11y' --profile selenium_chrome_headless
