name: Cucumber Tests

on:
  push:
  pull_request:

jobs:
  cucumber:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      # Do not install production/staging-only gems in test environment
      BUNDLE_WITHOUT: "production staging"
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: password
      CANVAS_URL: http://bcourses.test.instructure.com/
      CHROME_DATA_DIR: /tmp/chrome-data-cucumber
      COVERAGE: "true"
      SELENIUM_HEADLESS: "true"
      SELENIUM_DRIVER_VERSION: stable

    steps:
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .tool-versions
        bundler-cache: true
    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    - name: Setup Database
      run: bundle exec rails db:setup
    - name: Create Chrome data directory
      run: mkdir -p /tmp/chrome-data-cucumber
    - name: Run non-JavaScript Cucumber tests
      run: |
        bundle exec cucumber features/ --profile rack_test
    - name: Run JavaScript Cucumber tests
      run: |
        DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        bundle exec cucumber features/ --profile javascript
