name: Build Specs

on: [push, pull_request]

jobs:
  build:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DB_USER: postgres
      DB_PASSWORD: password
      RAILS_ENV: test
      RUBY_ENV: test
      # Rails secret management
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      # Canvas configuration
      CANVAS_URL: http://bcourses.test.instructure.com/
      # Canvas authentication variables
      CANVAS_TEST_USERNAME: ${{ secrets.CANVAS_TEST_USERNAME }}
      CANVAS_TEST_PASSWORD: ${{ secrets.CANVAS_TEST_PASSWORD }}
      CANVAS_TEST_NAME: ${{ secrets.CANVAS_TEST_NAME }}
      # Add debugging for Capybara
      CAPYBARA_DEBUG: true
      HEADLESS: true
    steps:
    - uses: actions/checkout@v1
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true
    - name: Download and install Code Climate test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: Run before-build command
      run: ./cc-test-reporter before-build
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    - name: Setup Rails environment
      run: |
        gem install bundler
        bundle config set --local deployment 'true'
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create db:schema:load
        bundle exec rails db:migrate
    - name: Setup Chrome for testing
      uses: browser-actions/setup-chrome@latest
    - name: Run RSpec tests
      run: bundle exec rspec --tag ~a11y
    - name: Run Cucumber tests
      run: bundle exec cucumber --tags 'not @a11y and not @skip'
      
    - name: Upload test screenshots and logs if failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          tmp/capybara/
          log/test.log

    - name: Run after-build command
      run: |
        ./cc-test-reporter after-build --exit-code $?
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}