name: RuboCop

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    env:
      # Do not install production/staging-only gems in test environment
      BUNDLE_WITHOUT: "production staging default test"
    name: Ruby Linting
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop
